# This file will be configured to contain variables for CPack. These variables
# should be set in the CMake list file of the project before CPack module is
# included. The list of available CPACK_xxx variables and their associated
# documentation may be obtained using
#  cpack --help-variable-list
#
# Some variables are common to all generators (e.g. CPACK_PACKAGE_NAME)
# and some are specific to a generator
# (e.g. CPACK_NSIS_EXTRA_INSTALL_COMMANDS). The generator specific variables
# usually begin with CPACK_<GENNAME>_xxxx.


set(CPACK_BUILD_SOURCE_DIRS "/home/steven/work/reCamera_demo/yolo_6d_pose/sscma-example-sg200x/solutions/sesg-project/yolo_6d_pose;/home/steven/work/reCamera_demo/yolo_6d_pose/sscma-example-sg200x/solutions/sesg-project/yolo_6d_pose/build_local")
set(CPACK_CMAKE_GENERATOR "Unix Makefiles")
set(CPACK_COMPONENT_UNSPECIFIED_HIDDEN "TRUE")
set(CPACK_COMPONENT_UNSPECIFIED_REQUIRED "TRUE")
set(CPACK_DEBIAN_FILE_NAME "DEB-DEFAULT")
set(CPACK_DEBIAN_PACKAGE_ARCHITECTURE "riscv64")
set(CPACK_DEBIAN_PACKAGE_CONTROL_EXTRA "/home/steven/work/reCamera_demo/yolo_6d_pose/sscma-example-sg200x/solutions/sesg-project/yolo_6d_pose/control/preinst;/home/steven/work/reCamera_demo/yolo_6d_pose/sscma-example-sg200x/solutions/sesg-project/yolo_6d_pose/control/postinst;/home/steven/work/reCamera_demo/yolo_6d_pose/sscma-example-sg200x/solutions/sesg-project/yolo_6d_pose/control/prerm;/home/steven/work/reCamera_demo/yolo_6d_pose/sscma-example-sg200x/solutions/sesg-project/yolo_6d_pose/control/postrm")
set(CPACK_DEBIAN_PACKAGE_MAINTAINER "techsupport@seeed.cc")
set(CPACK_DEFAULT_PACKAGE_DESCRIPTION_FILE "/usr/local/share/cmake-3.23/Templates/CPack.GenericDescription.txt")
set(CPACK_DEFAULT_PACKAGE_DESCRIPTION_SUMMARY "model_detector built using CMake")
set(CPACK_GENERATOR "DEB")
set(CPACK_INSTALL_CMAKE_PROJECTS "/home/steven/work/reCamera_demo/yolo_6d_pose/sscma-example-sg200x/solutions/sesg-project/yolo_6d_pose/build_local;model_detector;ALL;/")
set(CPACK_INSTALL_PREFIX "/usr/local")
set(CPACK_MODULE_PATH "")
set(CPACK_NSIS_DISPLAY_NAME "model_detector 0.1.1")
set(CPACK_NSIS_INSTALLER_ICON_CODE "")
set(CPACK_NSIS_INSTALLER_MUI_ICON_CODE "")
set(CPACK_NSIS_INSTALL_ROOT "$PROGRAMFILES")
set(CPACK_NSIS_PACKAGE_NAME "model_detector 0.1.1")
set(CPACK_NSIS_UNINSTALL_NAME "Uninstall")
set(CPACK_OUTPUT_CONFIG_FILE "/home/steven/work/reCamera_demo/yolo_6d_pose/sscma-example-sg200x/solutions/sesg-project/yolo_6d_pose/build_local/CPackConfig.cmake")
set(CPACK_PACKAGE_CONTACT "techsupport@seeed.cc")
set(CPACK_PACKAGE_DEFAULT_LOCATION "/")
set(CPACK_PACKAGE_DESCRIPTION_FILE "/usr/local/share/cmake-3.23/Templates/CPack.GenericDescription.txt")
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "model_detector built using CMake")
set(CPACK_PACKAGE_FILE_NAME "model_detector--Linux-riscv64")
set(CPACK_PACKAGE_INSTALL_DIRECTORY "model_detector 0.1.1")
set(CPACK_PACKAGE_INSTALL_REGISTRY_KEY "model_detector 0.1.1")
set(CPACK_PACKAGE_NAME "model_detector")
set(CPACK_PACKAGE_RELOCATABLE "true")
set(CPACK_PACKAGE_VENDOR "Seeed Technology Co.,Ltd.")
set(CPACK_PACKAGE_VERSION "0.1.1")
set(CPACK_PACKAGE_VERSION_MAJOR "0")
set(CPACK_PACKAGE_VERSION_MINOR "1")
set(CPACK_PACKAGE_VERSION_PATCH "1")
set(CPACK_RESOURCE_FILE_LICENSE "/usr/local/share/cmake-3.23/Templates/CPack.GenericLicense.txt")
set(CPACK_RESOURCE_FILE_README "/usr/local/share/cmake-3.23/Templates/CPack.GenericDescription.txt")
set(CPACK_RESOURCE_FILE_WELCOME "/usr/local/share/cmake-3.23/Templates/CPack.GenericWelcome.txt")
set(CPACK_SET_DESTDIR "OFF")
set(CPACK_SOURCE_GENERATOR "TBZ2;TGZ;TXZ;TZ")
set(CPACK_SOURCE_OUTPUT_CONFIG_FILE "/home/steven/work/reCamera_demo/yolo_6d_pose/sscma-example-sg200x/solutions/sesg-project/yolo_6d_pose/build_local/CPackSourceConfig.cmake")
set(CPACK_SOURCE_RPM "OFF")
set(CPACK_SOURCE_TBZ2 "ON")
set(CPACK_SOURCE_TGZ "ON")
set(CPACK_SOURCE_TXZ "ON")
set(CPACK_SOURCE_TZ "ON")
set(CPACK_SOURCE_ZIP "OFF")
set(CPACK_SYSTEM_NAME "Linux")
set(CPACK_THREADS "1")
set(CPACK_TOPLEVEL_TAG "Linux")
set(CPACK_WIX_SIZEOF_VOID_P "8")

if(NOT CPACK_PROPERTIES_FILE)
  set(CPACK_PROPERTIES_FILE "/home/steven/work/reCamera_demo/yolo_6d_pose/sscma-example-sg200x/solutions/sesg-project/yolo_6d_pose/build_local/CPackProperties.cmake")
endif()

if(EXISTS ${CPACK_PROPERTIES_FILE})
  include(${CPACK_PROPERTIES_FILE})
endif()
